[package]
name = "kleio"
version = "0.0.1"
edition = "2021"
rust-version = "1.65"


[dependencies]
async-trait = "0.1.58"
chrono = "0.4.23"
domain = { package = "domain", path = "../../../domain" }
macros = { package = "kleio_macros", path = "./macros" }
sea-orm = "0.10.0"
