[package]
name = "kleio"
version = "0.0.1"
edition = "2021"
rust-version = "1.65"
description = "Kleio"
license = "MIT"


[dependencies]
async-trait = "0.1.58"
chrono = "0.4.23"
kleio-macros = { path = "../kleio-macros", version = "0.0.1", default-features = false }
sea-orm = "0.10.0"
